### ISSUE TITLE
Uncaught TypeError: Invalid Point: (NaN, -1)

### ISSUE THREAD

**Issue by ghost** [lakrme/atom-levels#18]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.4 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [levels](https://github.com/lakrme/atom-levels) package 0.5.2

### Stack Trace

Uncaught TypeError: Invalid Point: (NaN, -1)

```
At C:\Users\eduardo\AppData\Local\atom\app-1.19.4\resources\app\node_modules\text-buffer\lib\point.js:63

TypeError: Invalid Point: (NaN, -1)
    at Function.module.exports.Point.assertValid (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/text-buffer/lib/point.js:63:21)
    at TextBuffer.module.exports.TextBuffer.clipPosition (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/text-buffer/lib/text-buffer.js:1139:19)
    at TextBuffer.module.exports.TextBuffer.clipRange (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/text-buffer/lib/text-buffer.js:1127:26)
    at MarkerLayer.module.exports.MarkerLayer.markRange (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/text-buffer/lib/marker-layer.js:217:52)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.markBufferRange (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:105:58)
    at TextEditor.module.exports.TextEditor.markBufferRange (~/AppData/Local/atom/app-1.19.4/resources/app/src/text-editor.js:1852:44)
    at AnnotationManager.module.exports.AnnotationManager.addAnnotationForExecutionIssue (/packages/levels/lib/annotation-manager.coffee:27:26)
    at LevelCodeEditor.module.exports.LevelCodeEditor.addExecutionIssue (/packages/levels/lib/level-code-editor.coffee:242:24)
    at LevelCodeEditor.module.exports.LevelCodeEditor.readExecutionIssueFromTypedMessage (/packages/levels/lib/level-code-editor.coffee:238:10)
    at /packages/levels/lib/level-code-editor.coffee:57:8
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Terminal.module.exports.Terminal.updateTypedMessageBufferOnDidCreateNewLine (/packages/levels/lib/terminal.coffee:313:18)
    at /packages/levels/lib/terminal.coffee:60:8
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TerminalBuffer.module.exports.TerminalBuffer.didCreateNewLine (/packages/levels/lib/terminal-buffer.coffee:217:14)
    at TerminalBuffer.module.exports.TerminalBuffer.newLine (/packages/levels/lib/terminal-buffer.coffee:56:6)
    at Terminal.module.exports.Terminal.newLine (/packages/levels/lib/terminal.coffee:243:13)
    at /packages/levels/lib/execution-manager.coffee:116:19
```

### Commands

```
     -3:00.3.0 levels-debugger-ruby:toggle-debugger-view (input.hidden-input)
     -2:23 core:confirm (div.line)
     -2:07.7.0 levels:start-execution (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
busy-signal 1.4.3 
emmet 2.4.3 
intentions 1.1.5 
jquery-snippets 11.0.0 
language-haml 0.25.1 
levels 0.5.2 
levels-debugger-ruby 0.5.0 
levels-language-ruby 0.5.2 
linter 2.2.0 
linter-ruby 1.2.6 
linter-ui-default 1.6.8 
pigments 0.40.2 
prettier-atom 0.38.0 
scss-media-queries 0.4.0 
scss-snippets 0.6.0 
```

**Comment by matthesjh** [comment]
Thank you for submitting this issue!

But can you please provide some further information or steps to reproduce the error, e.g. the selected level or the text typed into the terminal. Currently, I am unable to reproduce the error.
