### ISSUE TITLE
Failed to activate the levels package

### ISSUE THREAD

**Issue by Kirchberg** [lakrme/atom-levels#19]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.4
**Thrown From**: [levels](https://github.com/lakrme/atom-levels) package 0.6.0

### Stack Trace

Failed to activate the levels package

```
At Emitter has been disposed

Error: Emitter has been disposed
    at Emitter.on (/Users/programmer/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:1209755)
    at Workspace.onDidEnterWorkspace (/packages/levels/lib/workspace.js:26:25)
    at /packages/levels/lib/terminal-panel-view.js:152:47)
    at WorkspaceManager.setUpWorkspace (/packages/levels/lib/workspace-manager.js:29:30)
    at Object.activate (/packages/levels/lib/main.js:11:22)
    at Package.activateNow (/Users/programmer/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:3295584)
    at measure (/Users/programmer/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:3294996)
    at Package.measure (/Users/programmer/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:3292606)
    at activationPromise.activationPromise.Promise (/Users/programmer/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:3294856)
    at new Promise (<anonymous>)
    at Package.activate (/Users/programmer/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:3294799)
    at PackageManager.activatePackage (/Users/programmer/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:382285)
    at installDependencies (/packages/ide-ruby/node_modules/atom-package-deps/lib/index.js:50:33)
```

### Commands

```
     -9:46.4.0 core:select-all (input.hidden-input)
     -9:45.8.0 core:backspace (input.hidden-input)
     -9:45.5.0 core:paste (input.hidden-input)
     -9:18.6.0 debugger:show-launch-dialog (input.hidden-input)
     -9:10.5.0 core:cancel (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  5x -3:56.2.0 core:backspace (input.hidden-input)
     -3:55.2.0 core:confirm (input.hidden-input)
     -2:18.3.0 core:save (input.hidden-input)
     -2:11.8.0 debugger:show-launch-dialog (input.hidden-input)
     -1:55.4.0 core:cancel (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
ide-ruby 0.4.0 
levels 0.6.0 
levels-debugger-ruby 0.5.8 
levels-language-ruby 0.5.8 
platformio-ide-terminal 2.9.4 
w3c-validation 0.4.0 
```

**Comment by matthesjh** [comment]
It looks like this error is related to the `ide-ruby` package. Can you please disable the package and check whether the `levels` package can be loaded successfully.
