### ISSUE TITLE
Invalid XML Error

### ISSUE THREAD

**Issue by JTiko** [lakrme/atom-levels#5]
Wenn ich folgendes kleines Programm auf Sprachlevel 1 oder 2 teste, dann kommt es zu einem Laufzeitfehler:

```
def menu (a)
  correct = false
  while correct do
    correct = 42 > 0 && 42 <= a.size;
  end;
end;
```

Hier die kopierte Fehlermeldung:

**Atom Version**: 1.0.10
**System**: Debian GNU/Linux
**Thrown From**: [levels](https://github.com/lakrme/atom-levels) package, v0.0.1
### Stack Trace

Uncaught Error: Invalid XML: <message type="error" data-source="parser" data-row="3" data-col="18">
<head>
example3.lrb:3:18: Parser error:
</head>
<body>
  Error at (Line:3, Colum:18): I couldn't parse your program. Things I couldn't read: 

   while correct do 
   correct = 42 > 0 && 42 <= a . size ; 
   end ; 
   end ; 
   eof
  . Common mistakes: Forgot a ';', 'end;'?'. Check the parenthesis'.
</body>
</message>

```
At /net/medoc/home/jrt/atom-levels/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:250

Error: Invalid XML: <message type="error" data-source="parser" data-row="3" data-col="18">
<head>
example3.lrb:3:18: Parser error:
</head>
<body>
  Error at (Line:3, Colum:18): I couldn't parse your program. Things I couldn't read: 

   while correct do 
   correct = 42 > 0 && 42 <= a . size ; 
   end ; 
   end ; 
   eof
  . Common mistakes: Forgot a ';', 'end;'?'. Check the parenthesis'.
</body>
</message>

  at Function.jQuery.extend.error (/net/medoc/home/jrt/atom-levels/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:250:9)
  at Function.jQuery.parseXML (/net/medoc/home/jrt/atom-levels/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:7542:10)
  at Terminal.module.exports.Terminal.readTypedMessage (/net/medoc/home/jrt/atom-levels/lib/terminal.coffee:301:27)
  at Terminal.module.exports.Terminal.updateTypedMessageBufferOnDidCreateNewLine (/net/medoc/home/jrt/atom-levels/lib/terminal.coffee:286:25)
  at /net/medoc/home/jrt/atom-levels/lib/terminal.coffee:60:8
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TerminalBuffer.module.exports.TerminalBuffer.didCreateNewLine (/net/medoc/home/jrt/atom-levels/lib/terminal-buffer.coffee:211:14)
  at TerminalBuffer.module.exports.TerminalBuffer.newLine (/net/medoc/home/jrt/atom-levels/lib/terminal-buffer.coffee:56:6)
  at TerminalBuffer.module.exports.TerminalBuffer.write (/net/medoc/home/jrt/atom-levels/lib/terminal-buffer.coffee:146:8)
  at Terminal.module.exports.Terminal.write (/net/medoc/home/jrt/atom-levels/lib/terminal.coffee:238:13)
  at Socket.<anonymous> (/net/medoc/home/jrt/atom-levels/lib/execution-manager.coffee:60:17)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)

```
### Commands

```
  9x -3:54 core:move-right (atom-text-editor.editor.is-focused)
     -3:51.7.0 core:move-left (atom-text-editor.editor.is-focused)
  9x -3:49.9.0 core:delete (atom-text-editor.editor.is-focused)
     -3:43.4.0 core:save (atom-text-editor.editor.is-focused)
     -3:41 levels:start-execution (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -3:38.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:37.5.0 core:save (atom-text-editor.editor.is-focused)
     -3:36.1.0 levels:start-execution (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -2:45 levels:toggle-level-select (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -2:41.8.0 levels:start-execution (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -2:39.1.0 levels:toggle-level-select (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -2:35.1.0 levels:start-execution (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -2:33.2.0 levels:toggle-level-select (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -2:29.2.0 levels:start-execution (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -0:32.1.0 core:copy (atom-text-editor.editor.is-focused)
     -0:00.7.0 levels:start-execution (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "levels": {}
}
```
### Installed Packages

``` coffee
# User
levels, v0.0.1

# Dev
No dev packages
```

**Comment by lakrme** [comment]
Sollte jetzt behoben sein. Hatte nur vergessen Zeichen wie `<` und `>` korrekt zu escapen.

Danke für die ausführliche Beschreibung!

**Comment by JTiko** [comment]
Ja, funktioniert jetzt!
